### PR TITLE
Add IBM org

### PR DESCRIPTION
**Pull request by ckadner**
There currently are 241 repositories under the IBM org

### CODE REVIEW

**Comment by stevemart** [comment]
I'm not sure if this should be added. @christo4ferris do you have an opinion?

**Comment by ckadner** [comment]
@stevemart -- Just for my education, what are the criteria for deciding which IBM orgs should be added here? If an org has too many repositories that should not be advertised, should individual repositories be added here. What are the criteria for or against adding repositories? i.e. minimum number of non-IBM contributors, popularity, how much activity has it, how does it fit with IBM's mission, ...? If there are such criteria, maybe those should be listed on the README.

I'm asking because there is a long list of not currently listed IBM orgs and an even longer list of IBM repositories that could/should be included here.

**Comment by ajdlinux** [comment]
I agree with @ckadner - it would be nice to have some more clarity around what the intention of the ibm.github.io project index is meant to be.

For example. in Power Systems, we are the primary and sometimes exclusive contributors/maintainers of many projects under the umbrella of the OpenPOWER Foundation - would it be helpful to have those listed?

**Comment by stevemart** [comment]
@ckadner @ajdlinux thanks for chiming in. Historically ibm.github.io was for listing all open source projects by IBMers. That was fine for a while, but this year we've had a push to try and consolidate repos to github.com/IBM. @christo4ferris, @duglin and I have a TODO to see how we can make registering repos from IBMers as self-service as possible, and to take a second look at what we can do with ibm.github.io going forward.

**Comment by stevemart** [comment]
this was done in #127 and #128

**Pull request closed without merging**
