### PR TITLE
Center aligned search box.

### PR DESCRIPTION
**Pull request by imjog**
Currently search box is right aligned. I aligned search box to Center. It is look great in center and more user friendly. We can give it a try.

### CODE REVIEW

**Comment by imjog** [comment]
@stevemart Please have a look on this. thank you :)

**Comment by stevemart** [comment]
@imjog can you post a screenshot of what it looks like? I don't see a reason why we shouldn't change it, looks like it was right-aligned from the first commit.

**Comment by imjog** [comment]
@stevemart yes it was right aligned from first commit. We can use this centered style if it look great. I just try change. Here is screenshot:
1. Desktop screen:
desktop-searchbox
2. Mobile screen:
ibm-mobile-screen-searchbox

**Comment by stevemart** [comment]
@imjog nit pick: I'd also be OK with making the box longer. @christo4ferris thoughts?

**Comment by imjog** [comment]
@stevemart on mobile screen, making box longer will look great.

**Comment by imjog** [comment]
It will look like this after making box longer:
screen shot 2017-10-05 at 01 10 25

**Comment by Nitair** [comment]
For the mobile view I would add:
`padding: 2px;`
`@media screen and (max-width:768px){
	label.search span {
	float: none;
	margin: auto;
	padding: 2px;
	display: table;
	}
}`
which does center "Search" nicely.

snapshot2

**Comment by imjog** [comment]
@Nitair wider box looking more nice to me.

**Comment by Nitair** [comment]
@imjog, as requested with wider box

snapshot3

by adding 
`label.search {
	width: 100%;
}`

under

`@media screen and (max-width:768px)`

and removing

`padding-right: 0px;`

in

`.search`

**Comment by imjog** [comment]
@Nitair it is looking really nice. @stevemart your views?

**Comment by stevemart** [comment]
LGTM

**Pull request merged**
