### PR TITLE
Add organization zvmexporter and repository zvm_exporter

### PR DESCRIPTION
**Pull request by yrhee**
OSSC Proposal number: SYS144920160509
Project name: z/VM Exporter
Proposer: Ye Na Rhee/Germany/IBM
Proposer backups: Juergen Leopold/Germany/IBM

### CODE REVIEW

**Comment by christo4ferris** [comment]
@yrhee This LGTM but needs to be rebased so that it can be merged. Thanks

**Comment by christo4ferris** [comment]
@yrhee please rebase and resolve any merge conflicts... thanks

**Comment by stevemart** [comment]
I'm cleaning up old PRs -- @yrhee I checked the zvmexporter org and not much is going on there since 2016. Please confirm if this change is still desired.

**Comment by stevemart** [comment]
Closing PR as it's inactive

**Pull request closed without merging**
