### PR TITLE
Format index.html

### PR DESCRIPTION
**Pull request by jdmaturen**
Removed hard tabs. Ran index.html through IntelliJ's reformat code. Removed extra `</div>`s.

### CODE REVIEW

**Comment by jdmaturen** [comment]
cc @christo4ferris perhaps.

**Comment by jdmaturen** [comment]
Bump?

**Comment by christo4ferris** [comment]
sorry, please rebase - otherwise LGTM

**Comment by jdmaturen** [comment]
Code in master seems reasonably formatted, gonna close for now.

**Pull request closed without merging**
