### PR TITLE
Added feature to select more or less repos

### LINKED ISSUE #53: Main page has severe performance issues when loading repos
Viewing ibm.github.io results in a complete slowdown of Firefox 46.0.1 and Chrome 51.0.2704.54 on OSX 10.11.5. Loading the repos on the page seems to be causing lots of performance issues.

### PR DESCRIPTION
**Pull request by Nitair**
## Description
- First things first: closes #53 
- This change does increase performance because he does not load 1000+ repos at visiting site
- If an user opens site he will see 4 recently updated repos and 20 other repos which is defined as default. I guess this should be default, because if you enter this site as mobile phone user which uses mobile data it gonna burn your data a little bit. I also edited how many repos we COULD show at the header.

> ~~https://user-images.githubusercontent.com/10914774/32388493-29a440c0-c0c8-11e7-84ae-22f6391ad401.png~~ (old)

image

- User has the option to select `Show more` to show all repos. This causes that your browser puts a hash (`https://localhost/#showall`) after a reload, which was necessary because of javascript limitations.
- User also has option to revert this view with `Show less` which changes back to a view (also removes hash -> `https://localhost/`) of 20 repos
- Both buttons are matching the whole design and they also are optimized for mobile view (iPhone X as well, lol)
- Important note: If you search for a repo which is not shown if you only see 20 repos, you will not find that. In this case you have to select "Show more" which is working.

Mobile view (an URL because its gonna destroy my description)

> ~~https://user-images.githubusercontent.com/10914774/32388548-4eb44194-c0c8-11e7-8598-d50d728af459.png~~ (old)

> https://user-images.githubusercontent.com/10914774/32391556-cf0d19c4-c0d2-11e7-9301-079622f4d8ed.png

### Todo
- ~~Matching search bar with both buttons to make them look nicely in a row~~
- ~~Match mobile view again....~~
- ~~Changing text from `REPOS(20) CLICK 'SHOW MORE' TO SEE OTHER (1116) REPOS` to `SHOWING 20 REPOS. CLICK 'SHOW MORE' TO SEE OTHER 1116 REPOS`~~

@stevemart, what do you think about this?

### CODE REVIEW

**Comment by stevemart** [comment]
@Nitair i think it works for the desktop, but not crazy about the mobile version, how about this for mobile? (keep in mind i'm not a UI guy :) )

screen shot 2017-11-03 at 3 07 08 pm

**Comment by Nitair** [comment]
@stevemart which device are you using? Maybe I missed something or should rewrite mobile view again. :/

**Comment by stevemart** [comment]
@Nitair haha, that was my attempt at a mockup, but i see how that it is pretty close to your new implementation. I was looking at the old one earlier (https://user-images.githubusercontent.com/10914774/32388548-4eb44194-c0c8-11e7-8598-d50d728af459.png (old)) and wanted the boxes to be bigger.

**Comment by stevemart** [comment]
This also would close #53 potentially

**Comment by Nitair** [comment]
Oh yeah. Didn't notice that.

**Comment by Nitair** [comment]
@stevemart , I'm also not an UI guy haha :D

**Comment by stevemart** [comment]
@Nitair i appreciate the PRs, trust me!

**Comment by Nitair** [comment]
@stevemart all fine :) btw this site looks very nice right now. I pretty like that.

**Comment by stevemart** [comment]
@Nitair agreed! the code finally looks nice, too :)

**Comment by srl295** [comment]
language nit: I think it should be more vs  _fewer_ instead of _less_. See https://english.stackexchange.com/questions/495/less-vs-fewer

**Pull request merged**
